// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOM4IBHOF_RRmT8GlnrfXZEyGaJSBYl0I',
    appId: '1:719992577476:web:3c855bff713f9139979891',
    messagingSenderId: '719992577476',
    projectId: 'mdn777-bbed6',
    authDomain: 'mdn777-bbed6.firebaseapp.com',
    storageBucket: 'mdn777-bbed6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoUQOKGurob9yxxkjlRg3h4tCtNiHRkeY',
    appId: '1:719992577476:android:63ae80f57088be7a979891',
    messagingSenderId: '719992577476',
    projectId: 'mdn777-bbed6',
    storageBucket: 'mdn777-bbed6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBufwgenn3oGJGTfUt7-YipcAHOVNcO6k0',
    appId: '1:719992577476:ios:29dc67381ff3709b979891',
    messagingSenderId: '719992577476',
    projectId: 'mdn777-bbed6',
    storageBucket: 'mdn777-bbed6.firebasestorage.app',
    iosBundleId: 'com.example.mdn777',
  );
}
